"""added homework_file

Revision ID: f7434727564c
Revises: 
Create Date: 2021-04-18 08:16:43.590219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7434727564c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('homework_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework', 'homework_file')
    # ### end Alembic commands ###
